global:
  resolve_timeout: 25m

route:
  group_by:
    - alertname

  group_wait: 5s
  group_interval: 5s
  repeat_interval: 5s

  routes:
    - match:
        severity: super-critical
      receiver: 'web_hook_super_critical'
      continue: true

    - match:
        team: webhook-devs
      receiver: 'web_hook_team'

  receiver: 'web_hook_default'

receivers:
  - name: 'web_hook_default'
    webhook_configs:
    - url: 'http://echoalert:8080/default'
      send_resolved: true

  - name: 'web_hook_super_critical'
    webhook_configs:
    - url: 'http://echoalert:8080/super_critical'
      send_resolved: true

  - name: 'web_hook_team'
    webhook_configs:
    - url: 'http://echoalert:8080/team'
      send_resolved: true
